# Generated by Django 3.1.7 on 2021-03-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My6StockTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stock_code', models.TextField(blank=True, null=True)),
                ('stock_name', models.TextField(blank=True, null=True)),
                ('current_price', models.TextField(blank=True, null=True)),
                ('fluctuation_rate', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('foreigner_investor', models.TextField(blank=True, null=True)),
                ('trading_volume', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'my6_stock_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyStockTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('stock_code', models.TextField(blank=True, null=True)),
                ('stock_name', models.TextField(blank=True, null=True)),
                ('current_price', models.TextField(blank=True, null=True)),
                ('fluctuation_rate', models.TextField(blank=True, null=True)),
                ('created_at', models.TextField(blank=True, null=True)),
                ('foreigner_investor', models.TextField(blank=True, null=True)),
                ('trading_volume', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'my_stock_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(blank=True, max_length=20, null=True)),
                ('stock_name', models.CharField(blank=True, max_length=20, null=True)),
                ('current_price', models.CharField(blank=True, max_length=20, null=True)),
                ('fluctuation_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.CharField(blank=True, max_length=20, null=True)),
                ('foreigner_investor', models.CharField(blank=True, max_length=20, null=True)),
                ('trading_volume', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'stock_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('name', models.CharField(db_column='NAME', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
